/* SniffingCoffee database used as a baseline script from this location: https://gist.github.com/bertwagner/ea7d33bb4663649a53b138ee0a6af737 */

CREATE DATABASE SniffingCoffee;
GO

USE SniffingCoffee;
GO

DROP TABLE IF EXISTS dbo.CoffeeInventory
CREATE TABLE dbo.CoffeeInventory
(
	ID int IDENTITY(1,1),
	CoffeeName VARCHAR(100),
	CoffeePrice DECIMAL(4,2),
	CoffeeDescription VARCHAR(500),
	CreateDate DATETIME2 DEFAULT GETDATE()
);
GO

CREATE NONCLUSTERED INDEX IX_CoffeeName ON dbo.CoffeeInventory (CoffeeName) INCLUDE (CoffeePrice, CoffeeDescription);
GO

INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Costa Rica Tarrazu SWP Decaf',7.34,'Impressive acidity, like white grape juice. Liquid brown sugar, honey wheat bread, rice crispy treats, and caramel popcorn. As espresso, you''d be hard pressed to guess it''s a decaf! Super versatile. City to Full City+.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Costa Rica Helsar Asdrubal Chavez',6.10,'Asdrubal Chavez''coffee is restrained, sturdy, and with balance of sweetness and bittering components: toasted hazelnut, black tea, roasted malt, cacao, chocolate sponge cake. Full City - Full City+. Good espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Costa Rica Familia Bonillia',6.30,'Honey wheat puff and cocoa aromatics, move into flavors of cinnamon-dusted walnut, Jordan almonds, bittersweet chocolate, and fruited hints. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('El Salvador Finca Las Animas',5.95,'A compact flavor profile, maple walnut, sugar browning notes, and loads of bittersweet chocolate. Body, balance, and sweet. Good as espresso. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('El Salvador Finca Santa Julia Bourbon',5.95,'Santa Julia is sure to garner universal acclaim, a real crowd pleaser. Raw sugar, roasted nut, and cinnamon allude to granola, with hints of hazelnut, and dried apple. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Guatemala Xinabajul Producers',6.60,'Caramel sugar sweetness, cocoa powder-dusted almonds, and crisp apple accent. A balanced coffee with tea-like brightness. Cocoa flavors build with roast, and Full City and beyond are true dual-use. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Guatemala Antigua Pulcal Inteligente Lot 1',6.75,'Turbinado sugar to almond past sweetness, apple like acidity, delicate pear note, black tea with lemon, orange rind, and high % cacao. A superb brewed coffee across the roast spectrum. City to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Guatemala Antigua Finca Pavon',6.75,'Finca Pavon offers up flavors of high % cacao bar with black currant, along with dark grape and grape skins. Brown sugar sweetness with mild yet clean fruit juice-like acidity. City+ to Full City. SO Espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Mexico Organic Santo Domingo La Cascada',5.40,'This is a coffeecoffee, a low-acid, balanced cup. Understated fruit accents, core bittersweetness of burned caramel, apple and cherimoya hints. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Mexico Organic Tenejapa Kulaktik Coop',5.50,'Winey flavors of grape and peach, rustic date sugar, and a toasted coconut note are noted in City/C+ roasting, a mild black olive-like acidity, and walnut accent note in the finish. City to Full City.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Nicaragua Finca Buenos Aires Caturra',5.95,'Raw sugar and vanilla, roasted almond, and a dusting of milk chocolate to bittersweet cacao powder. Crowd-pleasing, balanced, bodied, low-acid cup that works well as dual-use. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Nicaragua Acopio Suyatal',5.90,'Suyatal has understated, yet persistent sweetness all the way up to 2nd snaps. Bittering cocoa and raw sugars find near perfect balance, with citrus rind, and toasted nut. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Nicaragua Buenos Aires Maracaturra Lot 1',7.25,'City to City+ roasts yield balanced caramel and roasted almond core flavors, topped off with accents of honey, chamomile florals, dried apple and apricot, cilantro, and tea-like brightness. City to City+.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Panama Boquete Finca San Sebastian',6.40,'Balance of sweet and bittering tones make this a crowd favorite, dark caramel, red apple, toffee nut, black tea, and crisp apple-like acidity. Roasted nut aroma. City+ to Full City.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Brazil Fazenda do Sertao Yellow Bourbon',5.70,'Layered sugar and nut notes come off like sweetened almond milk, and honey-glazed almond, and baker''s cocoa and hickory notes accent the finish. An approachable Brazil favorable in middle to dark roasting. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Brazil Dry Process Mirante Peaberry',5.80,'Peach fruit leather, unsulfered apricot pair well with a core of roasted nut, molasses, and bittersweet cocoa. Surprisingly clean finish for Brazilian coffee! Great brew in middle roasting. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Brazil Santa Lucia Yellow Bourbon',5.75,'Classic Brazil characteristics of big body, low acidity, and balanced sweet to savory notes. Brown sugar, almond paste, walnut, peanut cookie, cocoa powder, tamarind, and leather. City+ to Vienna. Good for Espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Brazil Dry Process Fazenda Furnas',5.80,'Furnas is a big fruited cup with hefty sweetness: molasses, berry, ripe apple, barley malt, tamarind, banana bread, peanut-rolled dried strawberries. Great accent coffee for blending. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Colombia La Plata Veredas Vecinos',6.05,'Veredas Vecinos boasts underlying raw cane juice sweetness, dried apple and persimmon hints, barley tea and black walnut in the finish. Impressive apple tea like acidity. City+ to Full City+.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Burundi Kayanza SWP Decaf',7.35,'One of the best decafs from this latest bunch, Burundi Kayanza SWP shows balanced bittersweetness, cheap dark chocolate, unsweetened baking cocoa, a dusting of cinnamon spice, subtle raisin and barley malt hits. City+ to Full City+. Excels as espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Burundi Kazosa N''Ikawa Station',6.30,'Incredible brewed, flavors of cherry, clove spice, sugarcane juice, marzipan, and a tart-sweet lemonade brightness highlight this Burundi cup. Such a refined cup profile with pointed finish. City to City+.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Burundi Rubanda Station',6.15,'Cane juice sweetness, with notes of dried cherry, orange tea, graham cracker, and a tart lemon accent. Floral and raspberry leaf hints mark the finish. Big body in the darker roast levels. City to Full City+. Great for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Burundi Kibumbu Kayokwe Lot 1',6.10,'Kayokwe is wonderful brewed in lighter roast shades, tea-like to lemon brightness, dark cranberry juice, complex baking spice notes, and resonant sweetness. A sparkling cup. City to City+.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Burundi Kayanza Dusangirijambo Coop',6.05,'City+ is a near perfect cup, dark currant, Lipton black tea, simple syrup, cocoa powder hints, and lemonade-like brightness. Ideal for light roasting. City to City+.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Ethiopia Kela Kochore Aseffa Station',6.70,'Kela Kochore shows a delicate, shimmering profile with a saturated red honey sweetness. Acidity is bright, and accentuated by flavors of pomelo, sweet lime, and mandarin orange. Overt florals add to this dynamic cup. City to Full City.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Ethiopia Shakiso Mormora Farm',6.65,'Mormora is a beautiful cup, refreshingin a way. Earl Grey with bergamot oil, rose water florals, citrus oil, and acidity that''s like sweet tea with lemon spritz. Best at City to City+ roast level.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Ethiopia Agaro -Duromina Cooperative',6.70,'2017 is a good year for Duromina, intense flavors of peach and nectarine, and orange marmalade note is attention grabbing. Deeper roasts pull out cacao bittersweetness, dark berry, plum, and citrus rind. Moderate acidity level. City to Full City. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Ethiopia Agaro -Nano Challa Cooperative',6.10,'Nano Challa is a structured cup, white honey sweetness with mild fruit and jasmine floral accent notes, ginger chews, citrus and Ricola-like dark herbal aspect. City to Full City. Good for SO espresso or accent coffee for espresso blending.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Ethiopia Dry Process Mormora Guji Highland',6.85,'So complex on it''s own, and a fantastic blend component, this DP shows a wide range of fruit flavors: melon, cooked rhubarb, strawberry milk, berry lambic, and more. Great from City to Full City. Good espresso blend component.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Ethiopia Duromina SWP Decaf',7.50,'As decaf, Duromina has much to celebrate. Intense caramelized sugar sweetness, peach muffin, fleshy fruit, lavender accent, and chocolate-covered wafer cookie. City to Full City. Nice accent coffee for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Rwanda Nyamasheke Mutovu Lot 1',6.25,'Mutovu is a fantastic brewed cup. Perfumed aromatics, butterscotch and sugarcane juice, baking spices, and fruited brightness. Accents of apple, stone fruit, Earl Grey tea, and vanilla-caramels. City to Full City.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Rwanda Rulindo Cooperatives SWP Decaf',7.25,'A balanced decaf at City+/Full City roasts, powdery baker''s cocoa bittering tones balanced by flavor of raw sugar and cinnamon, offset by savory accents, and a creamy Macadamia nut note. City+ to Full City. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Rwanda Kivu Kageyo Station Lot 1',6.20,'Kageyo is complex in light to middle roasts, cinnamon tea, sugarcane juice, vanilla bean, and red apple. Our City+ roast showed pomelo-like acidity, dark berry, cream soda, and baking spice. City to Full City. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Tanzania Mbeya Iyula AB',6.10,'Iyula has a clear cane sugar sweetness  with fruit to herbal accents , dark cranberry, licorice, and blood orange. Body is oily, and acidity grabby, like orange pulp. City+ to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Tanzania Tarime Town Peaberry',6.20,'This Peaberry is a real powerhouse, focused fruit notes, green grape and grape skins, candied citrus, and tea-like herbal flavors. Incredibly sweet underneath it all, and citrus-like acidity tying it all together. City to Full City.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Uganda Cheema Kapchorwa',5.50,'Heavily laden with layers of rich chocolate flavors, with dark stone fruits laying just beneath the surface. Minimally processed sugars balance cacao flavors, and body is extremely viscous. Full City to Full City+. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Uganda Mount Elgon Sipi Falls',5.60,'A unique Ugandan cup, grabby lemon citrus, barley tea and green apple top notes, a base bittersweetness of sucanat, rice syrup, and baker''s cocoa. Finishes with cedar aroma. City+ to Full City.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Zambia Kasama Estates',5.50,'The profile boasts pungent molasses, pipe tobacco leaves, rustic earth tones, and cooked rhubarb. Impressive body carries bittersweetness long in the aftertaste. City+ to Vienna')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('India Ratnagiri Pearl Mountain Peaberry',5.60,'Perhaps mild at first, Pearl Mountain Peaberry intensifies greatly as it cools. A sweet aroma leads to flavors of apple and grape, praline nut, stevia and lemon balm herbs, and powdery cocoa. City to Full City.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sumatra Lintong Boru Batak',6.60,'Lintong cup character: sweet malt syrups, mossy earth tones, green herbal notes, chicory root, pipe tobacco accents, baker''s cocoa along the way. Best with 48 to 72 hours rest. City+ to Vienna. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sumatra Lintong Pak Keisha',6.45,'Sumatra Pak Keisha has an IPA-like, hoppy aroma. Dark malt syrup, date sugar, peet, layers of earth-toned chocolate, and a subtle Darjeeling tea note. City+ to Vienna. Good for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Timor Leste Lacao Village',5.80,'Red raisin and honey wheat aromatics, baked banana bread, roasted nut and grain notes, Yerba Mate tea. Darker roasting brings out bittersweetness.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Timor Leste Organic Ermera Letefoho',5.90,'Letefoho reminds me of a wet-processed Central American coffee in many ways, raw sugar, honey-drizzled walnut, apple, with rye and cocoa powder in the finish. City+ to Full City+.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sweet Maria''s Majirani African Blend',6.85,'Intense espresso, bracing lemon acidity in middle roasts, high % Scharffen Berger chocolate, tart cranberry, lemon verbena. Acidity is toned down a bit at FC+, but still shows candied citrus flavors. City+ to FC+. Great espresso (see review).')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sweet Maria''s Espresso Monkey Blend',6.25,'We blend this for body, balanced between high and low tones, fruited-chocolate roast flavors, and slightly rustic fruited accent notes. Our roast goal is in the beginning stages of 2nd crack ... we never let it roll, so we recommend FC+ to light Vienna roast.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sweet Maria''s Ethiopiques Blend',6.85,'Incredible espresso and brewed coffee. Full City shots have ultra sweet chocolate flavors, along with citrus complexity, and prevalent floral characteristics. It''s definitely on the wilder side of espresso, but without being over the top. Fruit flavors shift and the sweet aftertaste lingers long. City to Full City depending on brew application. Great for espresso.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sweet Maria''s French Roast Blend',6.15,'Designed to endure the rigors of dark roasting, and produce excellent pungent tastes, attractive bittersweet/carbony flavors, and great body.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sweet Maria''s New Classic Espresso',6.50,'A classic, balanced espresso, but without the baggage of the old world espresso conventions ...and without robusta! The espresso has balanced bittersweet notes, thick and opaque body, almond and chocolate roast flavors, hints of peach tea, spice, jasmine.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sweet Maria''s Altiplano Blend',6.50,'Altiplano is extremely versatile in both roast level and brew applications. Lighter roasts show convincing levels of brightness and sweetness, with faint fruit and cocoa top notes. FC and beyond boosts body, sweetness, and chocolate roast complexity. City+ to Full City+. Great for espresso')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sweet Maria''s Decaf Espresso DonkeyBlend',7.45,'Fruited cup profile, some sweet bright accents, medium body. FC+ to a light Vienna is recommended.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Espresso Workshop #41 -Afiliate Romano',6.85,'A melding of bittersweet chocolate and fresh squeezed lemon are the bright spot of Afiliate Romano; Dutch cocoa, high % cacao bar, roasted nibs, semi-sweet chips, all cut through by tangy citric ''zing''. Full City to Full City+.')
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Sweet Maria''s Liquid Amber Espresso Blend',6.95,'A potent, pungent blend for espresso beverages. It''s ideal for milk drinks, as this intense bittersweet cuts through the steamed milk. Rustic sweetness, spice, savory notes, long aftertaste. Monsooned coffee and a small percentage of Robusta add crema and body. Vienna roast.') 
GO
INSERT INTO dbo.CoffeeInventory (CoffeeName, CoffeePrice, CoffeeDescription) VALUES ('Costa Rica La Casona -San Francisco 1900',6.20,'San Francisco 1800 has focused milk chocolate flavors, mild cinnamon stick and sugar browning notes, and cacao nib aftertaste. Chocolate/hazelnut spread at Full City. Full City to Full City+. SO Espresso.')
GO 10000 -- We are going to insert some duplicates here to skew the data in our table